import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/component/Provider";
import Nav from "@/component/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie Book",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
    <body>
      <Provider>
          <Nav />
          {children}
      </Provider>
    </body>
  </html>
  );
}
